### ISSUE TITLE
unexpected token import

### ISSUE THREAD

**Issue by josephkuruvilla** [johnymontana/movies-graphql-neo4j-server#1]
after installed the node modules and tried to run the server its showing the error as unexpected token import. how to get rid of this?

**Comment by johnymontana** [comment]
Usually, that is a problem with the code not being transpiled from ES6. How do you start the server? do you run `npm start`? That should use Babel to transpile:

```
"start": "nodemon ./server.js --exec babel-node",
```

**Comment by bmckinney** [comment]
I had the same problem. Add a .babelrc file with the following contents:

```javascript
{
  "presets":[
    "es2015",
    "stage-0"
  ]
}
```

**Comment by johnymontana** [comment]
Ah - looks like I forgot to check in `.babelrc` thanks for catching! Fixing now...
