### ISSUE TITLE
missing babel-preset-env dependency

### ISSUE THREAD

**Issue by bmckinney** [johnymontana/movies-graphql-neo4j-server#2]
Thanks for adding the .babelrc file. I think we're now missing the babel-preset-env dependency since I get thrown an "Error: Couldn't find preset "env" relative to directory..." error running `npm start`.

`npm i babel-preset-env -D` fixed it for me.

**Comment by johnymontana** [comment]
Thanks @bmckinney - I went ahead and updated several dependencies in 8c8a7f9, including `babel-preset-env`

**Comment by vikpande** [comment]
(For those who are trying to make it work recently)

@johnymontana , had similar issue but for me this one did the trick. 

First install the preset (using npm):

npm install --save-dev @babel/preset-env

Then add the below preset to your .babelrc

{
    presets: ["@babel/preset-env"]
}
